# Fado Adiça
#
# Joan Josep Ordinas Rosa <jordinas@gmail.com> 
#

include ../makefile.mak

# If harmony.ily changes guitar-harmony.ily must be touched
guitar-harmony.ily : harmony.ily
	touch $@

# vim:noet:sw=8:ts=8:ai
